// Sample model for preview.html (design work outside the app). Same shape as CONTRACT.md.
const now = Date.now();
const ref = (t) => ({ environmentId: "env-local", threadId: t });
const key = (t) => `env-local/${t}`;

export const mockModel = {
  version: 1,
  at: now,
  strip: true,
  shortcut: "Ctrl+Alt+Space",
  undoMs: 2500,
  stripY: 0.5,
  apps: [{ id: "default", name: "Personal" }, { id: "work", name: "Work" }], // two running apps; one app: no `apps` names and `app: null`
  counts: { attention: 2, working: 3, done: 1 },
  dots: [
    { threadKey: key("t1"), ref: ref("t1"), title: "Pricing page", project: "web", app: "Personal", status: "input", unread: false },
    { threadKey: key("t2"), ref: ref("t2"), title: "Run the migration", project: "api", app: "Work", status: "approval", unread: false },
    { threadKey: key("t3"), ref: ref("t3"), title: "Fix flaky login test", project: "web", app: "Personal", status: "working", unread: false },
    { threadKey: key("t4"), ref: ref("t4"), title: "Checkout speed", project: "web", app: "Personal", status: "working", unread: false },
    { threadKey: key("t5"), ref: ref("t5"), title: "Load test", project: "api", app: "Work", status: "working", unread: false },
    { threadKey: key("t6"), ref: ref("t6"), title: "Onboarding copy", project: "web", app: "Personal", status: "done", unread: true },
    { threadKey: key("t7"), ref: ref("t7"), title: "Release notes", project: "docs", app: "Work", status: "failed", unread: true },
  ],
  overflow: 0,
  cards: [
    {
      key: `${key("t1")}|q|req-1`,
      kind: "question",
      threadKey: key("t1"),
      ref: ref("t1"),
      title: "Pricing page",
      project: "web",
      app: "Personal",
      status: "input",
      at: now - 4 * 60_000,
      message: "I drafted three layouts for the pricing section. One question before I build it.",
      canReply: true,
      requestId: "req-1",
      questions: [
        {
          id: "layout",
          header: "Layout",
          question: "Which layout should the pricing section use?",
          multiSelect: false,
          allowCustom: true,
          options: [
            { label: "Three tiers with a yearly toggle", description: "Recommended: matches the current plans", value: "three-tiers" },
            { label: "One plan, one price", description: "Simplest page", value: "one-plan" },
            { label: "A comparison table", description: "Best for many features", value: "table" },
          ],
        },
      ],
    },
    {
      key: `${key("t2")}|a|req-2`,
      kind: "approval",
      threadKey: key("t2"),
      ref: ref("t2"),
      title: "Run the migration",
      project: "api",
      app: "Work",
      status: "approval",
      at: now - 60_000,
      message: "Migration 0042 adds an index on orders. The dry run on a copy took 3 s.",
      canReply: false,
      requestId: "req-2",
      approval: {
        requestKind: "command",
        detail: "bun run db:migrate --env production",
        appName: null,
        options: [
          { decision: "accept", label: "Approve", warning: null },
          { decision: "acceptForSession", label: "Allow for this session", warning: null },
          { decision: "decline", label: "Decline", warning: null },
        ],
      },
    },
    {
      key: `${key("t6")}|done|${now - 120_000}`,
      kind: "done",
      threadKey: key("t6"),
      ref: ref("t6"),
      title: "Onboarding copy",
      project: "web",
      app: "Personal",
      status: "done",
      at: now - 120_000,
      message: "Onboarding copy is in: three screens, tests green.\n\n- Screen 1: welcome\n- Screen 2: connect a repo\n- Screen 3: first task",
      canReply: true,
    },
    {
      key: `${key("t7")}|fail|run-9`,
      kind: "failed",
      threadKey: key("t7"),
      ref: ref("t7"),
      title: "Release notes",
      project: "docs",
      app: "Work",
      status: "failed",
      at: now - 30 * 60_000,
      message: "I started on the release notes.",
      canReply: true,
      error: "The provider session ended unexpectedly.",
    },
  ],
  agents: [
    { threadKey: key("t1"), ref: ref("t1"), title: "Pricing page", project: "web", app: "Personal", status: "input", unread: false, updatedAt: now - 4 * 60_000, branch: "pricing" },
    { threadKey: key("t2"), ref: ref("t2"), title: "Run the migration", project: "api", app: "Work", status: "approval", unread: false, updatedAt: now - 60_000, branch: "main" },
    { threadKey: key("t3"), ref: ref("t3"), title: "Fix flaky login test", project: "web", app: "Personal", status: "working", unread: false, updatedAt: now - 20_000, branch: "fix-login" },
    { threadKey: key("t6"), ref: ref("t6"), title: "Onboarding copy", project: "web", app: "Personal", status: "done", unread: true, updatedAt: now - 120_000, branch: null },
    { threadKey: key("t8"), ref: ref("t8"), title: "Rename settings keys", project: "api", app: "Work", status: "idle", unread: false, updatedAt: now - 3 * 3600_000, branch: "keys" },
  ],
};
